apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  common.properties: |-
    nats.urls={{ .Values.nats.serverUrls }}
    jersey.cors.headers=X-Requested-With,Authorization,Content-type,Accept-Version,Content-MD5,CSRF-Token,x-ijt,cache-control,baggage
    jersey.logging.exclude-entirely-uris=/health/liveness,/health/readiness,/metrics
  log4j2.xml: |-
     <Configuration packages="cd.connect.logging" monitorInterval="30" verbose="true">
        <Appenders>
          <Console name="STDOUT" target="SYSTEM_OUT">
            <ConnectJsonLayout/>
          </Console>
        </Appenders>

        <Loggers>
          <AsyncLogger name="io.featurehub" level="debug"/>
          <!--
          <AsyncLogger name="io.ebean.SQL" level="trace"/>
          <AsyncLogger name="io.ebean.TXN" level="trace"/>
          <AsyncLogger name="io.ebean.SUM" level="trace"/>
          <AsyncLogger name="io.ebean.DDL" level="trace"/>
          <AsyncLogger name="io.ebean.cache.QUERY" level="trace"/>
          <AsyncLogger name="io.ebean.cache.BEAN" level="trace"/>
          <AsyncLogger name="io.ebean.cache.COLL" level="trace"/>
          <AsyncLogger name="io.ebean.cache.NATKEY" level="trace"/>
          -->
          <AsyncLogger name="cd.connect.jersey.common.SpanWorkaroundFilter" level="warn"/>

          <AsyncLogger name="jersey-logging" level="trace" />

          <AsyncRoot level="info">
            <AppenderRef ref="STDOUT"/>
          </AsyncRoot>
        </Loggers>
     </Configuration>

