{{- if .Values.nats.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app.kubernetes.io/version: 4.2.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "featurehub.serviceAccountName" . }}
      containers:
        - name: nats
          image: "nats:2.1.7-alpine"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: nats
              containerPort: 4222
              protocol: TCP
            - name: monitoring
              containerPort: 8222
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 3
            httpGet:
              path: /
              port: monitoring
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 2
            timeoutSeconds: 3
            httpGet:
              path: /
              port: monitoring
          volumeMounts:
            - mountPath: /etc/nats-config
              name: app-config
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: nats-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
  {{- end }}

{{- end }}